apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bruno-site-minio-secret
  namespace: bruno
spec:
  encryptedData:
    accessKey: AgA7CmwwqqiFMIGVUpwdPGJUQZSDSHht3mV/b7t5giEqP3Ze6CPVsw4BgQOJJdVU/f3TgbU7L0DVDr01to64B744EEegHcTpx01aQXF2fTY65SDKFkqglso2QN8Bt2xuvA/8J/uymaM3vGT9fKvkMcpM4ZS/x4DBmYMCnS4yAGnLZuvqT3wvmoC7chURzRfrUjdjc2vXSffyFs9jXQYWlKuDrGFapb8ahM78yY5KSzDfA9559WWkwHyHnpo4dmiABHvEadd5PApdEvPDSBXtv3hLD8nOjAw23HR302n6tuFuKpFsTW5/FNs9pyAidF59ubbxJCDA+yeTFTDSLxQDMKdFFCQLJQG3WcsBjyzJOLPsqi4NOsCmUHZ1xwZeCG/VX98Rab16XmL6KUde/LyspL8X6pUz1tMTLH3L3a66Cte+VLRnWU5cvcosSLXfEguk79atyAjYKSPOZZCsgJyeAHtzrywRgXr0ZqBvv9JHPLdLnIHKMdpYDf4eRY7wYEQ6dpkxAnL4O14lYOH75F90N5Tzg51YhP9EtE8Ukbzk+aABIaV8RevVAH/RDb9tk2cb2yFY9+k1/ig3DcVezsxTVN4u5GAquy7WLDDJKTcnn+BKXYzsMzJ/MbYbc6flWYssFIsuhUSbBet7RLdgGcfoEBi0a40itiN2qD8j6NjasHPRlw+58+azJH4ZNqdFyHv7UmQjakDwdA/Pyazm
    secretKey: AgCR7JafBUb3TnBj0sFlPUqiEg56Sal9y7YTeJd3biiriUmx+vFV3FrIOouzNIEa6iXaJ1aDSgmL/+GXlSwpG7/vf74M1eSKlqePZuruWjyyVqNl/tqFvBxBmlP7uTE5mNVF1EpYMBrIzAlSAy0htDWY2xWF/AfnaG4PA1ErfPxL/TBXwbcDS5wsg0iDL79EwfOJMAXReukBZYrSrSzZmffXp1kIHfdz7HoEZ7yRGpyC3muz0gJ+iSk/wCPl+wbMS9clYzUaVHmtut1murIdGRqqtRRt/gNNZhCQ4xVeuIikyPOBYcho69PLcjmxiVdZ7SulkGQt+9kOy4XO1LzIu07ZNjdtaXN2UIS1ZU5IQDg9qJK3C/OaXHpeQQ7Y6bPEYr2yiqFRWKFaHgfgjt7onMy1t6MK+f8cW1HVEZIExjROkqzPdZ2Rmz5wJCBicdRQ5zX3zWE/Qun6nrC72YabZ9agK3MnKNxD0G5VZPbnhRMWjx0DZt99kMkDluTsayra3LBzWD2q8v6CdtxG5GjTgDKQoqm0a3iidiCd7tQrnBtP8AVOkUaCY/uuCB+LYkqOuQsxWhwnK+YCPIjVBxEA1qgMzdjQJLWyNXgTHjiPkYj84qdFJIj1vx652cmEAFPoJ+lgigwNsLi3jckQTqd2NcKR3bqDMV1VythfwvQLSaNG6nE9/D3fjtz+TE1L3v2p88xgFuc+w1cooU6L
  template:
    metadata:
      creationTimestamp: null
      name: bruno-site-minio-secret
      namespace: bruno
---
