apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: registry:5000/guestbook
      context: .
      docker: 
        dockerfile: ./skaffold/Dockerfile
deploy:
  kubectl:
    manifests:
      - ./skaffold/deployment.yaml
