apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}-master
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
      app: myapp
      component: redis
      tier: backend
      role: master
  template:
    metadata:
      labels:
        {{- include "redis.selectorLabels" . | nindent 8 }}
        app: myapp
        component: redis
        tier: backend
        role: master
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "redis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-exporter
          image: oliver006/redis_exporter:alpine
          ports:
            - name: exporter
              containerPort: 9121
              protocol: TCP
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.master.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.service.master.port }}
              protocol: TCP
          #livenessProbe:
            #httpGet:
              #path: /
              #port: redis
          #readinessProbe:
            #httpGet:
              #path: /
              #port: redis
          resources:
            {{- toYaml .Values.resources.myapp | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}-slave
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    app: myapp
    component: redis
    tier: backend
    role: slave
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
      app: myapp
      component: redis
      tier: backend
      role: slave
  template:
    metadata:
      labels:
        {{- include "redis.selectorLabels" . | nindent 8 }}
        app: myapp
        component: redis
        tier: backend
        role: slave
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "redis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-exporter
          image: oliver006/redis_exporter:alpine
          ports:
            - name: exporter
              containerPort: 9121
              protocol: TCP
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.slave.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: GET_HOSTS_FROM
            value: dns
          ports:
            - name: redis
              containerPort: {{ .Values.service.master.port }}
              protocol: TCP
          #livenessProbe:
            #httpGet:
              #path: /
              #port: redis
          #readinessProbe:
            #httpGet:
              #path: /
              #port: redis
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
