apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-master
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    app: myapp
    component: redis
    tier: backend
    role: master
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.master.port }}
      targetPort: {{ .Values.service.master.port }}
      protocol: TCP
      name: redis
    - port: 9121
      targetPort: 9121
      protocol: TCP
      name: exporter
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
    app: myapp
    component: redis
    tier: backend
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-slave
  labels:
    {{- include "redis.labels" . | nindent 4 }}
    app: myapp
    component: redis
    tier: backend
    role: slave
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.master.port }}
      targetPort: {{ .Values.service.master.port }}
      protocol: TCP
      name: redis
    - port: 9121
      targetPort: 9121
      protocol: TCP
      name: exporter
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
    app: myapp
    component: redis
    tier: backend
    role: slave
