---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "myapp-test"
  namespace: dev
  labels:
    kube-monkey/enabled: "false"
    kube-monkey/identifier: "monkey-victim"
    kube-monkey/mtbf: "2"
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"
    component: "myapp"
    role: "dev"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: myapp
      role: dev
  template:
    metadata:
      labels:
        component: myapp
        role: dev
    spec:
      serviceAccountName: "myapp-test"
      containers:
        - name: "myapp-dev"
          imagePullPolicy: Always
          image: "localhost:5000/myapp:dev"
          env:
          - name: API_CONTAINER_PORT 
            value: "8000"
          - name: DATABASE_TYPE
            value: "postgres"
          - name: DATABASE_HOST
            value: "postgres.postgres"
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_USER
            value: "myapp"
          - name: DATABASE_TYPE
            value: "supersecret"
          - name: DATABASE_NAME
            value: "myapp"
          ports:
            - name: "http"
              containerPort: 8000
              protocol: TCP
