---
apiVersion: v1
kind: Service
metadata:
  name: "myapp-dev"
  namespace: dev
  labels:
    component: "myapp"
    role: "dev"
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      nodePort: 30003
      name: http
  selector:
    component: "myapp"
    role: "dev"
---
---
apiVersion: v1
kind: Service
metadata:
  name: "prometheus-operated-nodeport-dev"
  namespace: dev
  labels:
    "prometheus": "prometheus-myapp-test"
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: web
      protocol: TCP
      nodePort: 30002
      name: web
  selector:
    "app" : "prometheus"
    "prometheus": "prometheus-myapp-test"
