---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lancedb-serverless

resources:
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - servicemonitor.yaml

labels:
  - pairs:
      app: lancedb-serverless
      app.kubernetes.io/name: lancedb-serverless

