kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: homelab
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  image: kindest/node:v1.34.0
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker
  image: kindest/node:v1.34.0
  labels:
    role: ai
  extraPortMappings:
  - containerPort: 30120 # jamie
    hostPort: 30120
    protocol: TCP
  - containerPort: 30121 # bruno
    hostPort: 30121
    protocol: TCP
  - containerPort: 30121
    hostPort: 30121
    protocol: TCP
  - containerPort: 30122
    hostPort: 30122
    protocol: TCP
  - containerPort: 30123
    hostPort: 30123
    protocol: TCP
  - containerPort: 30124
    hostPort: 30124
    protocol: TCP
- role: worker
  image: kindest/node:v1.34.0
  labels:
    role: serverless
  extraPortMappings:
  - containerPort: 30130
    hostPort: 30130
    protocol: TCP
  - containerPort: 30131
    hostPort: 30131
    protocol: TCP
  - containerPort: 30132
    hostPort: 30132
    protocol: TCP
- role: worker
  image: kindest/node:v1.34.0
  labels:
    role: observability
  extraPortMappings:
  - containerPort: 31040 # grafana
    hostPort: 30040
    protocol: TCP
  - containerPort: 30041 # prometheus
    hostPort: 30041
    protocol: TCP
  - containerPort: 30042 # loki
    hostPort: 30042
    protocol: TCP
  - containerPort: 30043 # tempo
    hostPort: 30043
    protocol: TCP
- role: worker
  image: kindest/node:v1.34.0
  labels:
    role: observability
  extraPortMappings:
  - containerPort: 31050 # grafana
    hostPort: 30050
    protocol: TCP
  - containerPort: 30051 # prometheus
    hostPort: 30051
    protocol: TCP
  - containerPort: 30052 # loki
    hostPort: 30052
    protocol: TCP
  - containerPort: 30053 # tempo
    hostPort: 30053
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: homelab
  namespace: kube-system
spec:
  type: NodePort
  port: 30000
  nodePort: 30000
  protocol: TCP
  selector:
    app: homelab