apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agent-sre

resources:
  - k8s-mcp-server.yaml

labels:
  - pairs:
      app.kubernetes.io/name: agent-sre
      app.kubernetes.io/component: mcp-server

