apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: rook-ceph-block
  #volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage }}
---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
  #name: local-pv-2
  #labels:
    #app: wordpress
#spec:
  #capacity:
    #storage: 2Gi
  #accessModes:
    #- ReadWriteOnce
  #hostPath:
    #path: /tmp/data/pv-2
