# Default values for kube-state-metrics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceMonitor:
  componentName: infra

replicaCount: 1

image:
  repository: quay.io/coreos/kube-state-metrics
  pullPolicy: IfNotPresent
  ports:
    httpMetrics:
      port: 8080
    telemetry:
      port: 8081

serviceAccount:
  create: true
  name: kube-state-metrics

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
   runAsNonRoot: true
   runAsUser: 1000
   readOnlyRootFilesystem: false

service:
  type: ClusterIP
  httpMetrics:
    port: 8080
  telemetry:
    port: 8081

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
