---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wordpress
  labels:
    component: {{ .Values.serviceMonitor.componentName }}
spec:
  selector:
    matchLabels:
      {{- include "wordpress.labels" . | nindent 6 }}
  endpoints:
  - port: exporter
