apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgAem+/Bmzqq8NzRaZOVRYApzICHf/+bO8e/S9RSc7PPedbrTBOk3XZHj/J+UxjbTyHdRc+K4lCLyCgmM6HZjJR4EW4IAEhLRxmk5g3+3Fxj9uszuy54l/MJfv+DTqaVKWzxlfUT7yNQkqTMNvfsnDGNtW7UhOMs1c1V5GJhfVBdVMyNn+mt7KgXeBQ6ulJsBzHelVlX+1HHioP2K/VROgPoRAGS3SEXrBwvOiw+d0aAlKsUyLz4gnheZnV4cEsylM9SLh2OrVHRoIb8p8tu6l0JII09UaWJdAR9V01Rwj1ekDK0ogL56sW5TEiuICmoP3267ahC33tlixJXqDeL1SkaWzIaYQwO0Q4RzHgn85KEGQaxFkstwyO9boP/j1bpVO1xvV1tPVgyWaY0qTPQbIUlNsdRNPWsCVbrlgXyKD/4/ht41k9lV3X91rG7SrP6tvUPAjUs2AvhrQVWll9afiHFTuYGsL2qYklNtfaENremzOFJsYHN9Wz9754oq453DOClbOepbQNqveLTSHjRF0J8cxAxXosrk4vdFIVpxeqktYHPSoLiRgfxk7ub0hYYSEQcrN6A96CyIrEFT+EifPZvNrdeyGLSg/YIOzIHQbUGg0i9DTCnSpGmkX2MhPMCGAqpar/lsMHHVEnOESP/k9SGyRtp7w+PuOdYj3cVpgTQCS9ENQcRqx01e8uA3DpyJ6xZs3YtJjFr5L7DNkkl8hP+KqpDC+5Gf/A3kIaPkkmrU1Zg//d/UAIXC+VVdw==
    MINIO_ROOT_USER: AgAIcyHIHpt2iVOnT0nfbN6mDk9a8IJHeI5wl110+5rw6Nl0cOfQ9dqTjjRoSd7gF4lLeCg8Ix1QBj8AM7CCHNW+SWVi8E7nuiDxzKHQdWxH8Quj/COZQMOnh5tIw1KYTG3t7FVlKtkSSZPOCKWW8cPlYtGb0tf/M36ze3FUSxLIetEXrHPjV3jw+yvzfIrb5EmNCbDJfhregU+5xXmJka23AV6yFDxgqZDrtBJ7Qu1L1tUi85KBprMv8nqw+pkLWBCMEoJyjo+hJqBhb8ib36Y+rPZQ7qrKuvzZ2LSWxoucfg8/pSl8rVYr3k1bBthO27YyvzwhAszLhFNx6uiQr3ny3Gy5f5RrHATdIfJE6cazX9M8UgcqtvTIOefE93EBRkMgWWCmnRVrt4zPcxeXx71fNZMY4kz9q9MniaohO65fMjcdsN4u2nvOu0km8ux4WSjkogOfCJV2FOtbmShFy5sel+e2rXFCj8Ag584URSsl+V/t22VF0DPPcWWeI2G3yVkd5YKeQZ3Il3NjftYtSiCyI9+paP9iSewfK79mumz0UVV7ozsFFUWDzUi63vhn8IZcSrtu9qMtquMG/2jDt0txoN6ZHqQyuSJzH/r7LzqudpqJ5EfgP2sddPTdTpwyEeBgafA6x0kw/o5Px3JlLPwR6ve66apNzT68iG2ecKmZ8Q6wPKiQhUFRvhQoOVOYrea3vnZFVPaY7+NT
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: minio
---
