---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # 📦 All namespaces
  - namespaces.yaml
  # 🔧 ScyllaDB Operator deployment
  - helmrelease-operator.yaml
  # 📊 ScyllaDB Manager deployment
  - helmrelease-manager.yaml
  # 🚀 ScyllaDB cluster deployment
  - helmrelease-scylla.yaml

