---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Phase 5: Mock Services
# Deploy mock services for testing and development

resources:
  - ../../infrastructure/notifi-test
  - ../../infrastructure/alerts/mocks
  - ../../infrastructure/localstack
  - ../../infrastructure/scylladb

