{
 "title": "MyApp",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Task Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(task_duration_seconds_bucket{code=\"201\",le=\"0.025\"}[1m])"
    }
   ]
  },
  {
   "title": "GoRoutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(go_goroutines[1m])" }
   ]
  },
  {
   "title": "Requests Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{code=\"200\"}[1m])"
    }
   ]
  }
 ]
}