apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: localhost:5000/myapp
      context: .
      docker: 
        dockerfile: ./build/Dockerfile
deploy:
  kubectl:
    manifests:
      - ./deploy/dev/*.yaml
