apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: localhost:5000/myapp
      context: .
      docker: 
        dockerfile: ./build/Dockerfile
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.ENV}}"
deploy:
  kubectl:
    manifests:
      - ./deploy/dev/*.yaml
