---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  labels:
    component: {{ .Values.serviceMonitor.componentName }}
    app: redis
    tier: backend
spec:
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: exporter
