---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  labels:
    {{- include "kube-state-metrics.prometheus" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kube-state-metrics.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http-metrics
