---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-rules-myapp
  labels:
    {{- include "myapp.prometheus" . | nindent 4 }}
spec:
  groups:
  - name: ./myapp.rules
    rules:
    - alert: MyAppPanicCount
      expr: rate(promhttp_metric_handler_requests_total{code="200"}[1m]) > 0.02
      for: 1m
      labels:
        severity: error
      annotations:
        summary: "{{`MyApp Usage Too High (instance {{ $labels.instance }})`}}"
        description: "{{`The amount of the requests is over the limit\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}`}}"
    - alert: MyAppPanicCount1
      expr: rate(create_duration_seconds_sum{code="201"}[1m]) / rate(create_duration_seconds_count{code="201"}[1m]) > 1
      for: 1m
      labels:
        severity: error
      annotations:
        summary: "{{`MyApp Create Slow (instance {{ $labels.instance }})`}}"
        description: "{{`The amount of time to create a record is over the limit\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}`}}"
