---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lancedb-pvc
  namespace: lancedb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi

