---
apiVersion: v1
kind: Service
metadata:
  name: lancedb
  namespace: lancedb
  labels:
    app: lancedb
    app.kubernetes.io/name: lancedb
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: lancedb

