apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-metrics
      port: {{ .Values.service.httpMetrics.port }}
      targetPort: http-metrics
    - name: telemetry
      port: {{ .Values.service.telemetry.port }}
      targetPort: telemetry
  selector:
    {{- include "kube-state-metrics.selectorLabels" . | nindent 4 }}
---
