"""
Prometheus metrics for agent-contracts.

All functions should import metrics from here to ensure consistency.
These metrics are designed to be consumed by Alertmanager for routing to notifi-services.
"""
from prometheus_client import Counter, Histogram, Gauge, Info

# =============================================================================
# CONTRACT PROCESSING METRICS
# =============================================================================

CONTRACTS_SCANNED = Counter(
    "agent_contracts_scanned_total",
    "Total contracts scanned",
    ["chain", "status"]  # status: success, error
)

CONTRACTS_FETCHED = Counter(
    "agent_contracts_fetched_total",
    "Total contracts fetched from block explorers",
    ["chain", "source", "status"]  # source: etherscan, alchemy, etc.
)

# =============================================================================
# VULNERABILITY METRICS (used for Alertmanager)
# =============================================================================

VULNERABILITIES_FOUND = Counter(
    "agent_contracts_vulnerabilities_total",
    "Total vulnerabilities found",
    ["chain", "severity", "vuln_type"]
)

VULNERABILITIES_CRITICAL = Counter(
    "agent_contracts_critical_vulns_total",
    "Critical vulnerabilities found (triggers immediate alert)",
    ["chain", "vuln_type", "contract_address"]
)

VULNERABILITIES_HIGH = Counter(
    "agent_contracts_high_vulns_total",
    "High severity vulnerabilities found",
    ["chain", "vuln_type", "contract_address"]
)

# =============================================================================
# EXPLOIT METRICS (used for Alertmanager)
# =============================================================================

EXPLOITS_GENERATED = Counter(
    "agent_contracts_exploits_generated_total",
    "Total exploits generated by LLM",
    ["chain", "status"]  # status: success, failed, timeout
)

EXPLOITS_VALIDATED = Counter(
    "agent_contracts_exploits_validated_total",
    "Exploits validated on Anvil fork (triggers CRITICAL alert)",
    ["chain", "vuln_type", "profit_potential", "contract_address"]
)

EXPLOITS_FAILED_VALIDATION = Counter(
    "agent_contracts_exploits_failed_validation_total",
    "Exploits that failed validation (false positives)",
    ["chain", "vuln_type"]
)

# =============================================================================
# PERFORMANCE METRICS
# =============================================================================

SCAN_DURATION = Histogram(
    "agent_contracts_scan_duration_seconds",
    "Time to scan contract",
    ["chain", "analyzer"],  # analyzer: slither, mythril, llm
    buckets=[1, 5, 10, 30, 60, 120, 300, 600]
)

LLM_INFERENCE_DURATION = Histogram(
    "agent_contracts_llm_inference_seconds",
    "LLM inference time",
    ["model", "operation"],  # operation: vuln_analysis, exploit_gen
    buckets=[1, 5, 10, 30, 60, 120, 180]
)

EXPLOIT_VALIDATION_DURATION = Histogram(
    "agent_contracts_exploit_validation_seconds",
    "Time to validate exploit on Anvil",
    ["chain"],
    buckets=[1, 5, 10, 30, 60, 120]
)

# =============================================================================
# RESOURCE METRICS
# =============================================================================

ACTIVE_SCANS = Gauge(
    "agent_contracts_active_scans",
    "Currently running scans",
    ["chain"]
)

PENDING_CONTRACTS = Gauge(
    "agent_contracts_pending_queue",
    "Contracts waiting to be scanned",
    ["chain"]
)

LLM_QUEUE_DEPTH = Gauge(
    "agent_contracts_llm_queue_depth",
    "LLM inference queue depth"
)

# =============================================================================
# COST METRICS
# =============================================================================

API_CALLS = Counter(
    "agent_contracts_api_calls_total",
    "External API calls made",
    ["service", "status"]  # service: etherscan, alchemy, anthropic
)

LLM_TOKENS_USED = Counter(
    "agent_contracts_llm_tokens_total",
    "LLM tokens consumed",
    ["model", "type"]  # type: input, output
)

# =============================================================================
# INFO METRICS
# =============================================================================

BUILD_INFO = Info(
    "agent_contracts_build",
    "Build information"
)


def init_build_info(version: str, commit: str):
    """Initialize build info metric."""
    BUILD_INFO.info({
        "version": version,
        "commit": commit,
    })

