{{- if .Values.serviceAccount.create -}}
---
# Token secret for GitHub Actions CI/CD
# This secret can be used to generate kubeconfig for GitHub Actions
apiVersion: v1
kind: Secret
metadata:
  name: homepage-github-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "homepage.serviceAccountName" . }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
{{- end }}

