---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-monkey-config-map
  namespace: {{ .Values.namespace }}
data:
  config.toml: |
    [kube-monkey]
    run_hour = 20
    start_hour = 21
    end_hour = 23
    blacklisted_namespaces = ["kube-system"]
    whitelisted_namespaces = ["default"]
    time_zone = "Australia/Melbourne"
    graceperiod_sec= 10
    [debug]
    enabled= true
    schedule_immediate_kill= true

# dry_run = true                           # Terminations are only logged
# run_hour = 8                             # Run scheduling at 8am on weekdays
# start_hour = 10                          # Don't schedule any pod deaths before 10am
# end_hour = 16                            # Don't schedule any pod deaths after 4pm
# blacklisted_namespaces = ["kube-system"] # Critical apps live here
# time_zone = "America/New_York"           # Set tzdata timezone example. Note the field is time_zone not timezone
