{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-monkey.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "kube-monkey.labels" . | nindent 4 }}
{{- end -}}
