apiVersion: v1
kind: ServiceAccount
metadata:
  name: jamie-slack-bot
  namespace: jamie
  labels:
    app.kubernetes.io/name: jamie-slack-bot
    app.kubernetes.io/part-of: jamie
    app.kubernetes.io/component: serviceaccount
