apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart-postgres.fullname" . }}
  annotations:
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        {{- include "chart-postgres.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: restore
        configMap:
          name: restore
      restartPolicy: Never
      containers:
      - name: createdb
        image: jbergknoff/postgresql-client
        volumeMounts:
        - name: restore
          mountPath: /tmp/restore
        command: ["/usr/bin/psql"]
        args: ['"postgresql://admin:admin123@gogs-postgres.kube-system:5432/testdb?sslmode=disable"', "<", "/tmp/restore/create.sql"]
      - name: restore-gogs
        image: jbergknoff/postgresql-client
        volumeMounts:
         - name: restore
           mountPath: /tmp/restore
        command: ["/usr/bin/psql"]
        args: ['"postgresql://admin:admin123@gogs-postgres.kube-system:5432/testdb?sslmode=disable"', "<", "/tmp/restore/gogs_file.sql"]
      - name: setup-exporter
        image: jbergknoff/postgresql-client
        volumeMounts:
          - name: restore
            mountPath: /tmp/restore
        command: ["/usr/bin/psql"]
        args: ['"postgresql://admin:admin123@gogs-postgres.kube-system:5432/testdb?sslmode=disable"', "<", "/tmp/restore/postgres_exporter.sql"]
