---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: oci://registry-1.docker.io/bitnamicharts/redis
  ref:
    semver: "22.x.x"
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    semver: "16.x.x"
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: rabbitmq-cluster-operator
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: oci://registry-1.docker.io/bitnamicharts/rabbitmq-cluster-operator
  ref:
    semver: "4.4.x"

