apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus-operator
  serviceMonitorSelector:
    matchLabels:
      component: {{ .Values.componentName }}
  resources:
    {{- toYaml .Values.resources.operated | nindent 4 }}
  enableAdminAPI: false
