apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-prometheus-operator.fullname" . }}
  labels:
    {{- include "chart-prometheus-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart-prometheus-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  type: {{ .Values.alertmanager.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: {{ .Values.alertmanager.service.nodePort }}
      name: http
  selector:
    alertmanager: alertmanager 
---
apiVersion: v1
kind: Service
metadata:
  name: proemtheus-operated-nodeport
  labels:
    {{- include "chart-prometheus.prometheus" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - port: 9090
    nodePort: 30200
    targetPort: web
    protocol: TCP
    name: web
  selector:
    app: prometheus
    prometheus: prometheus
