---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lucena-cloud-http
  namespace: cloudflare-tunnel
  labels:
    app: kube-prometheus-stack
    release: prometheus-operator
    component: canary-monitoring
spec:
  jobName: lucena-cloud-http
  prober:
    url: http://lucena.cloud
  targets:
    staticConfig:
      static:
      - lucena.cloud
  interval: 30s

---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lucena-cloud-https
  namespace: cloudflare-tunnel
  labels:
    app: kube-prometheus-stack
    release: prometheus-operator
    component: canary-monitoring
spec:
  jobName: lucena-cloud-https
  prober:
    url: https://lucena.cloud
  targets:
    staticConfig:
      static:
      - lucena.cloud
  interval: 30s

---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lucena-cloud-dns
  namespace: cloudflare-tunnel
  labels:
    app: kube-prometheus-stack
    release: prometheus-operator
    component: canary-monitoring
spec:
  jobName: lucena-cloud-dns
  prober:
    url: dns://1.1.1.1:53
  targets:
    staticConfig:
      static:
      - lucena.cloud
  interval: 30s

