
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflare-tunnel-metrics
  namespace: cloudflare-tunnel
  labels:
    app: kube-prometheus-stack
    release: prometheus-operator
    component: cloudflare-tunnel
spec:
  selector:
    matchLabels:
      app: cloudflared
      app.kubernetes.io/component: metrics
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
  namespaceSelector:
    matchNames:
    - cloudflare-tunnel