apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guestbook.fullname" . }}
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "guestbook.selectorLabels" . | nindent 6 }}
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        {{- include "guestbook.selectorLabels" . | nindent 8 }}
        app: guestbook
        tier: frontend
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "guestbook.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
          {{- if .Values.exporter.enabled }}
        - name: {{ .Chart.Name }}-exporter
          image: {{ .Values.exporter.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PORT
            value: {{ .Values.exporter.port | quote }}
          - name: SCRAPE_ADDR
            value: {{ .Values.exporter.scrapeAddress | quote }}
          ports:
            - name: exporter
              containerPort: {{ .Values.exporter.port }}
              protocol: TCP
          {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: GET_HOSTS_FROM
            value: dns
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources.guestbook | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
