apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
    component: app
    app: guestbook
    tier: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    {{- if .Values.exporter.enabled }}
    - port: {{ .Values.exporter.port }}
      targetPort: {{ .Values.exporter.port }}
      protocol: TCP
      name: exporter
    {{- end }}
  selector:
    {{- include "guestbook.selectorLabels" . | nindent 4 }}
    app: guestbook
    tier: frontend
