package main

import (
	"strconv"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

// =============================================================================
// 📊 PROMETHEUS METRICS DEFINITIONS
// =============================================================================

var (
	// HTTP request metrics
	httpRequestsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "http_requests_total",
			Help: "Total number of HTTP requests",
		},
		[]string{"method", "path", "status_code"},
	)

	httpRequestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "http_request_duration_seconds",
			Help:    "HTTP request duration in seconds",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"method", "path", "status_code"},
	)

	httpRequestSize = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "http_request_size_bytes",
			Help:    "HTTP request size in bytes",
			Buckets: []float64{100, 1000, 10000, 100000, 1000000},
		},
		[]string{"method", "path"},
	)

	httpResponseSize = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "http_response_size_bytes",
			Help:    "HTTP response size in bytes",
			Buckets: []float64{100, 1000, 10000, 100000, 1000000},
		},
		[]string{"method", "path", "status_code"},
	)

	// Database metrics
	dbConnectionsActive = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "db_connections_active",
			Help: "Number of active database connections",
		},
	)

	dbConnectionsIdle = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "db_connections_idle",
			Help: "Number of idle database connections",
		},
	)

	dbQueriesTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "db_queries_total",
			Help: "Total number of database queries",
		},
		[]string{"operation", "table"},
	)

	dbQueryDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "db_query_duration_seconds",
			Help:    "Database query duration in seconds",
			Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10},
		},
		[]string{"operation", "table"},
	)

	// Redis metrics
	redisOperationsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "redis_operations_total",
			Help: "Total number of Redis operations",
		},
		[]string{"operation", "status"},
	)

	redisOperationDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "redis_operation_duration_seconds",
			Help:    "Redis operation duration in seconds",
			Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1},
		},
		[]string{"operation"},
	)

	// LLM/AI metrics
	llmRequestsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "llm_requests_total",
			Help: "Total number of LLM requests",
		},
		[]string{"model", "status"},
	)

	llmRequestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "llm_request_duration_seconds",
			Help:    "LLM request duration in seconds",
			Buckets: []float64{0.1, 0.5, 1, 2, 5, 10, 30, 60, 120},
		},
		[]string{"model"},
	)

	llmTokensGenerated = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "llm_tokens_generated_total",
			Help: "Total number of tokens generated by LLM",
		},
		[]string{"model"},
	)

	// Business metrics
	projectViewsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "project_views_total",
			Help: "Total number of project views",
		},
		[]string{"project_id", "source"},
	)

	chatSessionsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "chat_sessions_total",
			Help: "Total number of chat sessions",
		},
		[]string{"status"},
	)

	// Application health metrics
	applicationUptime = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "application_uptime_seconds",
			Help: "Application uptime in seconds",
		},
	)

	applicationVersion = promauto.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "application_version_info",
			Help: "Application version information",
		},
		[]string{"version", "build_date", "git_commit"},
	)
)

// =============================================================================
// 🔧 METRICS MIDDLEWARE
// =============================================================================

// prometheusMiddleware provides Prometheus metrics for HTTP requests
func prometheusMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		start := time.Now()

		// Get request size
		requestSize := c.Request.ContentLength
		if requestSize < 0 {
			requestSize = 0
		}

		// Process request
		c.Next()

		// Calculate metrics
		duration := time.Since(start).Seconds()
		statusCode := strconv.Itoa(c.Writer.Status())
		method := c.Request.Method
		path := c.FullPath()

		// Use a default path for unregistered routes
		if path == "" {
			path = "unknown"
		}

		// Get response size
		responseSize := c.Writer.Size()
		if responseSize < 0 {
			responseSize = 0
		}

		// Record metrics
		httpRequestsTotal.WithLabelValues(method, path, statusCode).Inc()
		httpRequestDuration.WithLabelValues(method, path, statusCode).Observe(duration)
		httpRequestSize.WithLabelValues(method, path).Observe(float64(requestSize))
		httpResponseSize.WithLabelValues(method, path, statusCode).Observe(float64(responseSize))
	}
}

// =============================================================================
// 📈 METRICS HELPER FUNCTIONS
// =============================================================================

// RecordDatabaseMetrics records database operation metrics
func RecordDatabaseMetrics(operation, table string, duration time.Duration, success bool) {
	dbQueriesTotal.WithLabelValues(operation, table).Inc()
	dbQueryDuration.WithLabelValues(operation, table).Observe(duration.Seconds())
}

// RecordRedisMetrics records Redis operation metrics
func RecordRedisMetrics(operation string, duration time.Duration, success bool) {
	status := "success"
	if !success {
		status = "error"
	}

	redisOperationsTotal.WithLabelValues(operation, status).Inc()
	redisOperationDuration.WithLabelValues(operation).Observe(duration.Seconds())
}

// RecordLLMMetrics records LLM operation metrics
func RecordLLMMetrics(model string, duration time.Duration, success bool, tokensGenerated int) {
	status := "success"
	if !success {
		status = "error"
	}

	llmRequestsTotal.WithLabelValues(model, status).Inc()
	llmRequestDuration.WithLabelValues(model).Observe(duration.Seconds())

	if tokensGenerated > 0 {
		llmTokensGenerated.WithLabelValues(model).Add(float64(tokensGenerated))
	}
}

// RecordProjectView records a project view
func RecordProjectView(projectID string, source string) {
	projectViewsTotal.WithLabelValues(projectID, source).Inc()
}

// RecordChatSession records a chat session
func RecordChatSession(success bool) {
	status := "success"
	if !success {
		status = "error"
	}

	chatSessionsTotal.WithLabelValues(status).Inc()
}

// UpdateDatabaseConnectionMetrics updates database connection metrics
func UpdateDatabaseConnectionMetrics(active, idle int) {
	dbConnectionsActive.Set(float64(active))
	dbConnectionsIdle.Set(float64(idle))
}

// SetApplicationVersion sets the application version metrics
func SetApplicationVersion(version, buildDate, gitCommit string) {
	applicationVersion.WithLabelValues(version, buildDate, gitCommit).Set(1)
}

// UpdateUptime updates the application uptime metric
func UpdateUptime(uptime time.Duration) {
	applicationUptime.Set(uptime.Seconds())
}
