{{ if not .Values.vault.existingConfigName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}-config
  labels:
    {{- include "vault.labels" . | nindent 4 }}
data:
  config.json: |
    {{ .Values.vault.config | toJson }}
{{ end }}

