apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
    name: api
    nodePort: {{ .Values.service.nodePort }}
  {{- if .Values.serviceMonitor.enabled }}
  - port: 9410
    protocol: TCP
    targetPort: {{ .Values.serviceMonitor.podPortName }}
    name: metrics
  {{- end }}
  selector:
    {{- include "vault.selectorLabels" . | nindent 4 }}
