---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gogs
  labels:
    component: {{ .Values.serviceMonitor.componentName }}
spec:
  selector:
    matchLabels:
      {{- include "chart-gogs.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: gogs-port
