---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Phase 3: Serverless Platform
# Deploy Knative Operator and serverless components

resources:
  - ../rabbitmq-operator
  - ../k6-operator
  - ../knative-operator
  - ../knative-serving
  - ../knative-eventing