---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-fluentd
  labels:
    component: infra
spec:
  selector:
    matchLabels:
      {{- include "fluentd.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: exporter
