apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s-agent.yaml

commonLabels:
  component: agent
  app.kubernetes.io/name: sre-agent
  app.kubernetes.io/component: agent
  app.kubernetes.io/part-of: sre-agent-system

namespace: agent-sre

