apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus-operator
  serviceMonitorSelector:
    matchLabels:
      {{ include "chart-prometheus.prometheus" . | nindent 6 }}
  ruleSelector:
    matchLabels:
      {{ include "chart-prometheus.prometheus" . | nindent 6 }}
  resources:
    {{- toYaml .Values.resources.operated | nindent 4 }}
  enableAdminAPI: false
