---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-rules-redis
  labels:
    {{- include "redis.prometheus" . | nindent 4 }}
spec:
  groups:
  - name: ./redis.rules
    rules:
    - alert: Foo
      expr: Vector(1)
