apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: rook-ceph
  labels:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
spec:
  ports:
  - name: dashboard
    port: 9283
    protocol: TCP
    targetPort: 9283
    nodePort: 30500
  selector:
    app: rook-ceph-mgr
    rook_cluster: rook-ceph
  sessionAffinity: None
  type: NodePort
