# Default values for chart-postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

persistentVolumeClaim:
  storage: 3Gi

serviceMonitor:
  componentName: infra

replicaCount: 1

env:
  - name: POSTGRES_DB
    value: "myapp"
  - name: POSTGRES_USER
    value: "postgres"         
  - name: POSTGRES_PASSWORD
    value: "postgres"

image: 
  repository: postgres
  pullPolicy: IfNotPresent
  containerPort: 5432

exporter:
  enabled: false
  repository: wrouesnel/postgres_exporter:v0.8.0
  containerPort: 9187

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: postgres

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  #runAsNonRoot: true # postgres image runs as root
  #runAsUser: 1000
  capabilities:
    #drop:
      #- ALL
    add:
      # chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted
      - CHOWN             # change the owner of any file.
      - NET_RAW           # send a raw packet (e.g. ping).
      - NET_ADMIN         # manage network configuration.
      - NET_BIND_SERVICE  # open a port under 1024.
    
networkPolicy:
  enabled: true

service:
  type: NodePort
  port: 5432
  nodePort: 30009
  exporter:
    type: ClusterIP
    port: 9187

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
