apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s-mcp-server.yaml

namespace: jamie

commonLabels:
  app.kubernetes.io/name: jamie-mcp-server
  app.kubernetes.io/component: mcp-server
  app.kubernetes.io/part-of: jamie

