apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus-operated
  serviceMonitorSelector:
    matchLabels:
      {{- include "velero.prometheus" . | nindent 6 }}
  ruleSelector:
    matchLabels:
      {{- include "velero.prometheus" . | nindent 6 }}
  resources:
    {{- toYaml .Values.resources.prometheus | nindent 4 }}
  enableAdminAPI: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operated
  labels:
    {{ include "velero.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operated-nodeport
  labels:
    {{- include "velero.prometheus" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - port: 9090
    nodePort: 30300
    targetPort: web
    protocol: TCP
    name: web
  selector:
    app: prometheus
    prometheus: prometheus
