apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: velero
  labels:
    {{- include "velero.prometheus" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "velero.labels" . | nindent 6 }}
  endpoints:
  - honorLabels: true
    port: monitoring
