apiVersion: myapp.com/v1alpha1
kind: MyApp
metadata:
  name: myapp
spec:
  size: 3
  database_type: postgres
  database_name: myapp
  host: postgres.storage
  port: 5432
  user: postgres
  pass: postgres
  container_port: 8000
  watch:
    - namespace: storage
      deployments:
        - name: postgres
