# Default values for fluentd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/fluentd_elasticsearch/fluentd
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: fluentd

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 24231

resources:
  limits:
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}
