---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-kibana
  labels:
    {{- include "kibana.prometheus" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kibana.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: exporter
