apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart-postgres.fullname" . }}
  labels:
    {{- include "chart-postgres.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart-postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart-postgres.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "chart-postgres.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      containers:
        {{- if .Values.exporter.enabled }}
        - name: {{ .Chart.Name }}-exporter
          image: {{ .Values.exporter.repository }}
          env:
            - name: DATA_SOURCE_NAME
              value: postgresql://postgres_exporter:changeme@localhost:5432/postgres?sslmode=disable
          ports:
            - name: exporter
              containerPort: {{ .Values.exporter.containerPort }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: exporter
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: exporter
            initialDelaySeconds: 5
        {{- end }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/
              name: postgredb
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
