apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agent-bruno
  namespace: bruno
  labels:
    app: agent-bruno
spec:
  selector:
    matchLabels:
      app: agent-bruno
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

