# Default values for grafana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafanaLoki: 
  enabled: false # slows down bootstraping the monitoring pulling images.

serviceMonitor:
  componentName: infra

replicaCount: 1

image:
  grafana:
    repo: grafana/grafana
    containerPort: 3000
  grafanaLoki: 
    repo: grafana/loki:v1.1.0
    containerPort: 3100
  promtail: 
    repo: grafana/promtail:v1.1.0
    containerPort: 9080
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: grafana

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
   capabilities:
     drop:
     - ALL
   readOnlyRootFilesystem: false
   runAsNonRoot: true
   runAsUser: 1000

service:
  type: NodePort
  grafana:
    port: 3000
    nodePort: 30003
  grafanaLoki:
    port: 9080
    nodeport: 30004

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
