# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceMonitor:
  componentName: app

replicaCount: 1

image:
  master:
    repository: k8s.gcr.io/redis
  slave:
    repository: gcr.io/google_samples/gb-redisslave:v1
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: redis

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  master:
    port: 6379 
  slave:
    port: 6379

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
